spring.application.name=project1

spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_reservation
spring.datasource.username=postgres
spring.datasource.password = password
spring.datasource.driver-class-name= org.postgresql.Driver

#JPA Configuration
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update 
## later switch to validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.format_sql=true

#Server configuration
server.port=8080

#Connection Pooling
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

#Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

