# Application name used by SpringBoot
# Appears in logs, monitoring tools and application context
spring.application.name=project1  

# PostgreSQL database connection URL
# Connects SpringBoot to the hotel_reservation_db database
# running on localhost at port 5432
spring.datasource.url=jdbc:postgresql://localhost:5432/hotel_reservation_db

# Database password used for password
spring.datasource.username=postgres

# Database password used for authentication
spring.datasource.password=ssss

# PostgreSQL JDBC driver used to establish database connections
spring.datasource.driver-class-name=org.postgresql.Driver

# Specifies PostgreSQL as the target database platform
spring.jpa.database=POSTGRESQL

# Automatically updates database tables based on entity changes
# Existing data is preserved
#
# create -> Drops and recreated tables every startup
# create-drop -> Creates tables and drops them on shutdown
# update -> updates schema without deleting data
# validate -> only validates schema
spring.jpa.hibernate.ddl-auto=update

# Prints generated SQL queries in application logs
spring.jpa.show-sql=true

# Formats SQL queries for better readability in logs
spring.jpa.properties.hibernate.format_sql=true

# Enables detailed Hibernate SQL logging
# Useful for debugging and query analysis
logging.level.org.hibernate.SQL=DEBUG

# Secret key used for JWT token generation and validation
# Must remain confidential because anyone with this key
# can generate valid authentication tokens
jwt.secret=MyHotelReservationSystemSecretKeyForJwtAuthentication2026Project

# JWT token validity duration in milliseconds
# 18000000 ms = 30 minutes
jwt.expiration=1800000

logging.level.org.springframework.security=DEBUG



