package com.infotact.project1.model;

import com.infotact.project1.enums.PaymentStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import com.infotact.project1.enums.PaymentMethod;

/*
 * Represents a payment transaction for a reservation.
 * Stores payment gateway information and transaction status.
 * Designed to support Razorpay and other payment providers.
 */

@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "payments")
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long paymentId;

    // Reservation associated with this payment
    @ManyToOne
    @JoinColumn(name = "reservation_id", nullable = false)
    private Reservation reservation;

    // BigDecimal avoids floating-point precision issues in monetary calculations
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal amount;

    // Supports future multi-currency expansion
    @Column(nullable = false, length = 10)
    private String currency;

//    // Example: CARD, UPI, NET_BANKING, WALLET
//    @Column(nullable = false)
//    private String paymentMethod;

    // Selected payment method
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentMethod paymentMethod;

    // Example: Razorpay, Stripe
    @Column(nullable = false)
    private String paymentGateway;

    // Generated by payment gateway before payment initiation
    private String gatewayOrderId;

    // Generated by payment gateway after successful payment
    private String gatewayPaymentId;

    // Used to verify payment authenticity
    private String gatewaySignature;

    // Stored as STRING to keep enum values readable in the database
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private PaymentStatus paymentStatus;

    // Timestamp when payment was successfully completed
    private LocalDateTime paidAt;

    // Automatically managed audit timestamps
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(nullable = false)
    private LocalDateTime updatedAt;

    // Populate timestamps when payment record is created
    @PrePersist
    public void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    // Update timestamp whenever payment details change
    @PreUpdate
    public void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}